plugins:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - demo/_site/**/*
    - binstub/**/*
    - vendor/**/*
    - Gemfile*
    - git_tree.gemspec
  NewCops: enable

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/InitialIndentation:
  Exclude:
    - README.md
    - CHANGELOG.md
    - Gemfile*
    - git_tree.gemspec

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Exclude:
    - git_tree.gemspec

Lint/RedundantDirGlobSort:
  Enabled: false

Metrics/AbcSize:
  Max: 45

Metrics/BlockLength:
  Exclude:
    - git_tree.gemspec
    - spec/**/*
  Max: 35

Metrics/ClassLength:
  Exclude:
    - spec/**/*
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Exclude:
    - Rakefile
    - CHANGELOG.md
    - README.md
    - Gemfile*
    - exe/*

RSpec/ExampleLength:
  Max: 20

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SpecFilePathFormat:
  IgnoreMethods: true

RSpec/SubjectStub:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
