test:
  git_timeout: 7
  verbosity: 2
  default_roots:

development:
  git_timeout: 7
  verbosity: 2
  default_roots:

production:
  git_timeout: 300
  verbosity: 2
  default_roots: [sites, sitesUbuntu, work]
