test:
  git_timeout: 7,
  verbosity: ::Logging::NORMAL,
  default_roots:

development:
  git_timeout: 7,
  verbosity: ::Logging::NORMAL,
  default_roots:

production:
  git_timeout: 300,
  verbosity: ::Logging::NORMAL,
  default_roots: sites, sitesUbuntu, work
